"""add new constraint

Revision ID: 146de395d3a1
Revises: 6be61e30d172
Create Date: 2026-01-15 13:15:47.564383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '146de395d3a1'
down_revision: Union[str, Sequence[str], None] = '6be61e30d172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_passage_village_order'), 'roadmap_passages', type_='unique')
    op.create_unique_constraint('uq_passage_village_order', 'roadmap_passages', ['village_id', 'order_index', 'subject'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_passage_village_order', 'roadmap_passages', type_='unique')
    op.create_unique_constraint(op.f('uq_passage_village_order'), 'roadmap_passages', ['village_id', 'order_index'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
