"""passage table village restict changed to cascade

Revision ID: 44f84eef9f07
Revises: b2e76dc6437c
Create Date: 2026-01-18 12:47:46.469371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f84eef9f07'
down_revision: Union[str, Sequence[str], None] = 'b2e76dc6437c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('passages_village_id_fkey'), 'passages', type_='foreignkey')
    op.create_foreign_key(None, 'passages', 'buildings', ['village_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'passages', type_='foreignkey')
    op.create_foreign_key(op.f('passages_village_id_fkey'), 'passages', 'buildings', ['village_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
