"""user table timezone added

Revision ID: 7289ed09055
Revises: 7289ed0909dd
Create Date: 2026-02-13 01:19:13.933643

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7289ed09055'
down_revision: Union[str, Sequence[str], None] = '7289ed0909dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'text')
    op.add_column('questions', sa.Column('text', sa.String()))
    # ### end Alembic commands ###


def downgrade() -> None:
    ...