"""feat: order index removed

Revision ID: b2e76dc6437c
Revises: c4ac3cd62496
Create Date: 2026-01-18 02:08:27.071688

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2e76dc6437c'
down_revision: Union[str, Sequence[str], None] = 'c4ac3cd62496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('village_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('order_index', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['village_id'], ['buildings.id'], ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_passages_village_id'), 'passages', ['village_id'], unique=False)
    op.create_table('nodes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('passage_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('content', sa.Text(), nullable=True),
                    sa.Column('is_boss', sa.Boolean(), nullable=False),
                    sa.Column('config', sa.JSON(), nullable=False),
                    sa.Column('pass_score', sa.Integer(), nullable=True),
                    sa.Column('reward_coins', sa.Integer(), nullable=True),
                    sa.Column('reward_xp', sa.Integer(), nullable=True),
                    sa.CheckConstraint(
                        '(is_boss = false) OR (pass_score IS NOT NULL AND reward_coins IS NOT NULL AND reward_xp IS NOT NULL)',
                        name='ck_nodes_boss_fields_required'),
                    sa.CheckConstraint('NOT (is_boss = true AND user_id IS NOT NULL)',
                                       name='ck_nodes_boss_must_be_shared'),
                    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_nodes_passage', 'nodes', ['passage_id'], unique=False)
    op.create_index(op.f('ix_nodes_passage_id'), 'nodes', ['passage_id'], unique=False)
    op.create_index('ix_nodes_passage_user', 'nodes', ['passage_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_nodes_user_id'), 'nodes', ['user_id'], unique=False)
    op.create_index('uq_nodes_one_shared_boss_per_passage', 'nodes', ['passage_id'], unique=True,
                    postgresql_where=sa.text('is_boss = true AND user_id IS NULL'))
    op.drop_index(op.f('ix_roadmap_passage_bosses_node_id'), table_name='roadmap_passage_bosses')
    op.drop_index(op.f('ix_roadmap_passage_bosses_passage_id'), table_name='roadmap_passage_bosses')
    op.drop_table('roadmap_passage_bosses')
    op.drop_index(op.f('ix_nodes_passage_order'), table_name='roadmap_nodes')
    op.drop_index(op.f('ix_roadmap_nodes_passage_id'), table_name='roadmap_nodes')
    op.drop_index(op.f('ix_roadmap_nodes_user_id'), table_name='roadmap_nodes')
    op.drop_index(op.f('uq_nodes_one_boss_per_passage'), table_name='roadmap_nodes',
                  postgresql_where='(is_boss = true)')
    op.execute("DROP TABLE roadmap_nodes CASCADE")
    op.drop_index(op.f('ix_passage_village_order'), table_name='roadmap_passages')
    op.drop_index(op.f('ix_roadmap_passages_subject'), table_name='roadmap_passages')
    op.drop_index(op.f('ix_roadmap_passages_village_id'), table_name='roadmap_passages')
    op.drop_table('roadmap_passages')
    op.add_column('buildings',
                  sa.Column('subject', postgresql.ENUM('ENGLISH', 'READING', 'SCIENCE', 'MATH', name='subjectenum'),
                            nullable=True))
    op.add_column('buildings', sa.Column('next_building_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_buildings_next_building_id'), 'buildings', ['next_building_id'], unique=False)
    op.create_foreign_key(None, 'buildings', 'buildings', ['next_building_id'], ['id'], ondelete='SET NULL')
    op.drop_column('buildings', 'order_index')
    op.alter_column(
        'questions',
        'order_index',
        existing_type=sa.INTEGER(),
        default=1
    )
    op.drop_table(
        'questions',
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column(
            "node_id",
            sa.Integer(),
            sa.ForeignKey("nodes.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column(
            "order_index",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("1"),
        ),
    )

    op.create_index("ix_questions_node_id", "questions", ["node_id"])
    op.create_foreign_key(None, 'questions', 'nodes', ['node_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_castles_user_id_key'), 'user_castles', type_='unique')
    op.create_unique_constraint('uq_user_castles_user', 'user_castles', ['user_id'])
    op.drop_constraint(op.f('user_castles_castle_id_fkey'), 'user_castles', type_='foreignkey')
    op.create_foreign_key(None, 'user_castles', 'buildings', ['castle_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'user_node_progresses', 'nodes', ['node_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_village_id_subject_unique_village'), 'user_villages', type_='unique')
    op.create_index('ix_user_villages_user', 'user_villages', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_village', 'user_villages', ['user_id', 'village_id'])
    op.drop_constraint(op.f('user_villages_village_id_fkey'), 'user_villages', type_='foreignkey')
    op.create_foreign_key(None, 'user_villages', 'buildings', ['village_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('user_villages', 'subject')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_villages',
                  sa.Column('subject', postgresql.ENUM('ENGLISH', 'READING', 'SCIENCE', 'MATH', name='subjectenum'),
                            autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_villages', type_='foreignkey')
    op.create_foreign_key(op.f('user_villages_village_id_fkey'), 'user_villages', 'buildings', ['village_id'], ['id'],
                          ondelete='CASCADE')
    op.drop_constraint('uq_user_village', 'user_villages', type_='unique')
    op.drop_index('ix_user_villages_user', table_name='user_villages')
    op.create_unique_constraint(op.f('user_village_id_subject_unique_village'), 'user_villages',
                                ['user_id', 'village_id', 'subject'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'user_node_progresses', type_='foreignkey')
    op.create_foreign_key(op.f('user_node_progresses_node_id_fkey'), 'user_node_progresses', 'roadmap_nodes',
                          ['node_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_castles', type_='foreignkey')
    op.create_foreign_key(op.f('user_castles_castle_id_fkey'), 'user_castles', 'buildings', ['castle_id'], ['id'],
                          ondelete='CASCADE')
    op.drop_constraint('uq_user_castles_user', 'user_castles', type_='unique')
    op.create_unique_constraint(op.f('user_castles_user_id_key'), 'user_castles', ['user_id'],
                                postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_node_id_fkey'), 'questions', 'roadmap_nodes', ['node_id'], ['id'],
                          ondelete='CASCADE')
    op.alter_column('questions', 'order_index',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.add_column('buildings', sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'buildings', type_='foreignkey')
    op.drop_index(op.f('ix_buildings_next_building_id'), table_name='buildings')
    op.drop_column('buildings', 'next_building_id')
    op.drop_column('buildings', 'subject')
    op.create_table('roadmap_passages',
                    sa.Column('id', sa.INTEGER(),
                              server_default=sa.text("nextval('roadmap_passages_id_seq'::regclass)"),
                              autoincrement=True, nullable=False),
                    sa.Column('village_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('subject', postgresql.ENUM('ENGLISH', 'READING', 'SCIENCE', 'MATH', name='subjectenum'),
                              autoincrement=False, nullable=False),
                    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['village_id'], ['buildings.id'], name='roadmap_passages_village_id_fkey',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name='roadmap_passages_pkey'),
                    sa.UniqueConstraint('village_id', 'order_index', 'subject', name='uq_passage_village_order',
                                        postgresql_include=[], postgresql_nulls_not_distinct=False),
                    postgresql_ignore_search_path=False
                    )
    op.create_index(op.f('ix_roadmap_passages_village_id'), 'roadmap_passages', ['village_id'], unique=False)
    op.create_index(op.f('ix_roadmap_passages_subject'), 'roadmap_passages', ['subject'], unique=False)
    op.create_index(op.f('ix_passage_village_order'), 'roadmap_passages', ['village_id', 'order_index'], unique=False)
    op.create_table('roadmap_nodes',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('roadmap_nodes_id_seq'::regclass)"),
                              autoincrement=True, nullable=False),
                    sa.Column('passage_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('is_boss', sa.BOOLEAN(), autoincrement=False, nullable=False),
                    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
                    sa.Column('pass_score', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('reward_coins', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('reward_xp', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.CheckConstraint(
                        'is_boss = false OR pass_score IS NOT NULL AND reward_coins IS NOT NULL AND reward_xp IS NOT NULL',
                        name='ck_nodes_boss_fields_required'),
                    sa.ForeignKeyConstraint(['passage_id'], ['roadmap_passages.id'],
                                            name='roadmap_nodes_passage_id_fkey', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='roadmap_nodes_user_id_fkey',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name='roadmap_nodes_pkey'),
                    sa.UniqueConstraint('passage_id', 'order_index', name='uq_nodes_passage_order',
                                        postgresql_include=[], postgresql_nulls_not_distinct=False),
                    postgresql_ignore_search_path=False
                    )
    op.create_index(op.f('uq_nodes_one_boss_per_passage'), 'roadmap_nodes', ['passage_id'], unique=True,
                    postgresql_where='(is_boss = true)')
    op.create_index(op.f('ix_roadmap_nodes_user_id'), 'roadmap_nodes', ['user_id'], unique=False)
    op.create_index(op.f('ix_roadmap_nodes_passage_id'), 'roadmap_nodes', ['passage_id'], unique=False)
    op.create_index(op.f('ix_nodes_passage_order'), 'roadmap_nodes', ['passage_id', 'order_index'], unique=False)
    op.create_table('roadmap_passage_bosses',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('passage_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('node_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
                    sa.Column('pass_score', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('reward_coins', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('reward_xp', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['node_id'], ['roadmap_nodes.id'],
                                            name=op.f('roadmap_passage_bosses_node_id_fkey'), ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['passage_id'], ['roadmap_passages.id'],
                                            name=op.f('roadmap_passage_bosses_passage_id_fkey'), ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('roadmap_passage_bosses_pkey'))
                    )
    op.create_index(op.f('ix_roadmap_passage_bosses_passage_id'), 'roadmap_passage_bosses', ['passage_id'], unique=True)
    op.create_index(op.f('ix_roadmap_passage_bosses_node_id'), 'roadmap_passage_bosses', ['node_id'], unique=True)
    op.drop_index('uq_nodes_one_shared_boss_per_passage', table_name='nodes',
                  postgresql_where=sa.text('is_boss = true AND user_id IS NULL'))
    op.drop_index(op.f('ix_nodes_user_id'), table_name='nodes')
    op.drop_index('ix_nodes_passage_user', table_name='nodes')
    op.drop_index(op.f('ix_nodes_passage_id'), table_name='nodes')
    op.drop_index('ix_nodes_passage', table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_passages_village_id'), table_name='passages')
    op.drop_table('passages')
    # ### end Alembic commands ###
