"""init tables

Revision ID: bf1b92d9ac4c
Revises: 
Create Date: 2026-01-13 14:57:15.023996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1b92d9ac4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('svg', sa.String(), nullable=True),
    sa.Column('treasure_capacity', sa.Integer(), nullable=False),
    sa.Column('speed_production_treasure', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('VILLAGE', 'CASTLE', name='buildingtype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('current_score', sa.Integer(), nullable=False),
    sa.Column('target_score', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.DateTime(), nullable=False),
    sa.Column('has_onboard', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('current_xp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_passages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Enum('ENGLISH', 'READING', 'SCIENCE', 'MATH', name='subjectenum'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('village_id', 'order_index', name='uq_passage_village_order')
    )
    op.create_index('ix_passage_village_order', 'roadmap_passages', ['village_id', 'order_index'], unique=False)
    op.create_index(op.f('ix_roadmap_passages_subject'), 'roadmap_passages', ['subject'], unique=False)
    op.create_index(op.f('ix_roadmap_passages_village_id'), 'roadmap_passages', ['village_id'], unique=False)
    op.create_table('user_castles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('castle_id', sa.Integer(), nullable=False),
    sa.Column('treasure_amount', sa.Integer(), nullable=False),
    sa.Column('last_collect_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('taps_used_today', sa.Integer(), nullable=False),
    sa.Column('last_tap_reset_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['castle_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_villages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('treasure_amount', sa.Integer(), nullable=False),
    sa.Column('last_collect_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subject', sa.Enum('ENGLISH', 'READING', 'SCIENCE', 'MATH', name='subjectenum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['village_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'village_id', 'subject', name='user_village_id_subject_unique_village')
    )
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fund', sa.Integer(), nullable=False),
    sa.Column('fund_type', sa.Enum('COIN', 'CRYSTAL', name='fundtype'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_boss', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('pass_score', sa.Integer(), nullable=True),
    sa.Column('reward_coins', sa.Integer(), nullable=True),
    sa.Column('reward_xp', sa.Integer(), nullable=True),
    sa.CheckConstraint('(is_boss = false) OR (pass_score IS NOT NULL AND reward_coins IS NOT NULL AND reward_xp IS NOT NULL)', name='ck_nodes_boss_fields_required'),
    sa.ForeignKeyConstraint(['passage_id'], ['roadmap_passages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passage_id', 'order_index', name='uq_nodes_passage_order')
    )
    op.create_index('ix_nodes_passage_order', 'roadmap_nodes', ['passage_id', 'order_index'], unique=False)
    op.create_index(op.f('ix_roadmap_nodes_passage_id'), 'roadmap_nodes', ['passage_id'], unique=False)
    op.create_index(op.f('ix_roadmap_nodes_user_id'), 'roadmap_nodes', ['user_id'], unique=False)
    op.create_index('uq_nodes_one_boss_per_passage', 'roadmap_nodes', ['passage_id'], unique=True, postgresql_where=sa.text('is_boss = true'))
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['roadmap_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_node_id'), 'questions', ['node_id'], unique=False)
    op.create_table('roadmap_passage_bosses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('pass_score', sa.Integer(), nullable=False),
    sa.Column('reward_coins', sa.Integer(), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['roadmap_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passage_id'], ['roadmap_passages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_passage_bosses_node_id'), 'roadmap_passage_bosses', ['node_id'], unique=True)
    op.create_index(op.f('ix_roadmap_passage_bosses_passage_id'), 'roadmap_passage_bosses', ['passage_id'], unique=True)
    op.create_table('user_node_progresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('xp', sa.Float(), nullable=False),
    sa.Column('correct_answer', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['roadmap_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_node_progresses_node_id'), 'user_node_progresses', ['node_id'], unique=False)
    op.create_index(op.f('ix_user_node_progresses_user_id'), 'user_node_progresses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_node_progresses_user_id'), table_name='user_node_progresses')
    op.drop_index(op.f('ix_user_node_progresses_node_id'), table_name='user_node_progresses')
    op.drop_table('user_node_progresses')
    op.drop_index(op.f('ix_roadmap_passage_bosses_passage_id'), table_name='roadmap_passage_bosses')
    op.drop_index(op.f('ix_roadmap_passage_bosses_node_id'), table_name='roadmap_passage_bosses')
    op.drop_table('roadmap_passage_bosses')
    op.drop_index(op.f('ix_questions_node_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index('uq_nodes_one_boss_per_passage', table_name='roadmap_nodes', postgresql_where=sa.text('is_boss = true'))
    op.drop_index(op.f('ix_roadmap_nodes_user_id'), table_name='roadmap_nodes')
    op.drop_index(op.f('ix_roadmap_nodes_passage_id'), table_name='roadmap_nodes')
    op.drop_index('ix_nodes_passage_order', table_name='roadmap_nodes')
    op.drop_table('roadmap_nodes')
    op.drop_table('wallets')
    op.drop_table('user_villages')
    op.drop_table('user_castles')
    op.drop_index(op.f('ix_roadmap_passages_village_id'), table_name='roadmap_passages')
    op.drop_index(op.f('ix_roadmap_passages_subject'), table_name='roadmap_passages')
    op.drop_index('ix_passage_village_order', table_name='roadmap_passages')
    op.drop_table('roadmap_passages')
    op.drop_table('experiences')
    op.drop_table('users')
    op.drop_table('buildings')
    # ### end Alembic commands ###
