"""questions add order index

Revision ID: c4ac3cd62496
Revises: 146de395d3a1
Create Date: 2026-01-16 02:28:08.144819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ac3cd62496'
down_revision: Union[str, Sequence[str], None] = '146de395d3a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('order_index', sa.Integer(), default=1))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'order_index')
    # ### end Alembic commands ###
